from langgraph.graph import StateGraph, END
from backend.state import TeacherState, Question
from backend.vector_store import add_documents
from backend.llm import generate_json
import pypdf

# Node: PDF Extraction & Embedding
def extract_pdf_node(state: TeacherState):
    print(f"Extracting text from {state['pdf_path']}...")
    text = ""
    try:
        reader = pypdf.PdfReader(state['pdf_path'])
        for page in reader.pages:
            text += page.extract_text() + "\n"
    except Exception as e:
        print(f"Error reading PDF: {e}")
        text = "Error reading PDF content."

    # Chunk and Store in Qdrant
    # Simple chunking by paragraphs or fixed size
    chunks = [chunk for chunk in text.split('\n\n') if len(chunk) > 50]
    if chunks:
        add_documents(chunks, {"source": state['pdf_path']})
    
    return {"extracted_text": text}

# Node: Topic Segmentation (Simplified to just pass through for now, or use LLM)
def segment_topics_node(state: TeacherState):
    # For now, we'll just use the whole text or rely on the LLM to pick topics
    return {"topics": ["General Content"]} 

# Node: MCQ Generator
def generate_mcq_node(state: TeacherState):
    print(f"Generating {state['mcq_count']} MCQs...")
    
    prompt = f"""
    Based on the following text, generate {state['mcq_count']} multiple choice questions.
    The difficulty level should be mixed (Easy, Medium, Hard).
    
    Text Content (truncated):
    {state['extracted_text'][:5000]}
    
    Output format (JSON list of objects):
    [
        {{
            "id": 1,
            "text": "Question text",
            "options": ["A", "B", "C", "D"],
            "correct_answer": "Correct Option Text",
            "explanation": "Why it is correct",
            "difficulty": "Easy/Medium/Hard",
            "type": "MCQ",
            "topic": "Topic Name"
        }}
    ]
    """
    
    response = generate_json(prompt)
    questions = response if isinstance(response, list) else []
    
    # Assign IDs if missing
    for i, q in enumerate(questions):
        q['id'] = i + 1
        
    return {"generated_questions": questions}

# Node: Subjective Generator
def generate_subjective_node(state: TeacherState):
    if not state.get('include_subjective', False):
        return {}
    
    print("Generating subjective questions...")
    prompt = f"""
    Based on the following text, generate 3 subjective questions (Short Answer, Long Answer).
    
    Text Content (truncated):
    {state['extracted_text'][:5000]}
    
    Output format (JSON list of objects):
    [
        {{
            "id": 100,
            "text": "Question text",
            "options": null,
            "correct_answer": "Key points for the answer",
            "explanation": "Detailed explanation",
            "difficulty": "Hard",
            "type": "Subjective",
            "topic": "Topic Name"
        }}
    ]
    """
    
    response = generate_json(prompt)
    new_qs = response if isinstance(response, list) else []
    
    # Adjust IDs
    start_id = len(state['generated_questions']) + 1
    for i, q in enumerate(new_qs):
        q['id'] = start_id + i
        
    return {"generated_questions": state['generated_questions'] + new_qs}

# Node: Export Worksheet
def export_worksheet_node(state: TeacherState):
    print("Formatting worksheet...")
    from backend.tools import pdf_exporter
    
    # Create markdown version
    md = "# Worksheet\n\n"
    for q in state['generated_questions']:
        md += f"### Q{q['id']} ({q['difficulty']}): {q['text']}\n"
        if q.get('options'):
            for opt in q['options']:
                md += f"- [ ] {opt}\n"
        md += "\n"
        
    # Answer Key markdown
    key_md = "# Answer Key\n\n"
    for q in state['generated_questions']:
        key_md += f"**Q{q['id']}**: {q['correct_answer']}\n"
        key_md += f"*Explanation*: {q['explanation']}\n\n"
    
    # Generate PDF using tools
    pdf_path = pdf_exporter.create_worksheet_pdf(
        title="Worksheet - Generated by EduMind",
        questions=state['generated_questions'],
        answer_key=True,
        output_path=None  # Auto-generate path
    )
        
    return {
        "worksheet_markdown": md, 
        "answer_key_markdown": key_md,
        "pdf_path": pdf_path
    }

# Build Graph
workflow = StateGraph(TeacherState)

workflow.add_node("extract_pdf", extract_pdf_node)
workflow.add_node("segment_topics", segment_topics_node)
workflow.add_node("generate_mcq", generate_mcq_node)
workflow.add_node("generate_subjective", generate_subjective_node)
workflow.add_node("export_worksheet", export_worksheet_node)

workflow.set_entry_point("extract_pdf")
workflow.add_edge("extract_pdf", "segment_topics")
workflow.add_edge("segment_topics", "generate_mcq")
workflow.add_edge("generate_mcq", "generate_subjective")
workflow.add_edge("generate_subjective", "export_worksheet")
workflow.add_edge("export_worksheet", END)

teacher_graph = workflow.compile()
